<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class JobsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('job_positions')->insert(array(
            array('uuid' => Str::uuid(), 'name' => 'Aulas Particulares', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'RH - Recursos Humanos', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Filosofia', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Sociologia', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Magistério, Matéria p/', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Educação Infantil, Aux. de', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Período Integral', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Cozinheira/Cantina', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Tesouraria', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Tesouraria, Aux. de', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Inglês p/ Curso', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Matemática Pré-Vestibular', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Geografia', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'História Pre-Vestibular', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'TPD', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Educação Especial', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => '1°/5° Ano - Ens. Fundamental', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Alemão', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Artes/Ed. Artística', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Aulas Especiais', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Biblioteca, Auxiliar de', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Secretaria, Auxiliar de', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Bibliotecária (o)', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Biologia', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Biologia Pré-Vestibular', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Ciências', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Contabilidade', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Desenho Geométrico', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Direção', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Educação Física', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Educação Infantil', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Espanhol', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Estatística', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Física', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Francês', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Geografia Fundamental', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Geografia Médio', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'História', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'História Fundamental', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'História Médio', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Informática', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Inglês', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Inglês Fundamental II', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Inglês Médio', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Inspetor de Alunos', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Iso', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Italiano', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Matemática', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Matemática Fundamental', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Matemática Médio', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Org. Empresas', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Orientação Educacional', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Português', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Português Fundamental', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Português Médio', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Proc. de Dados', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Química', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Química Pré-Vestibular', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Secretária (o)', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Serviços Gerais', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Supervisão', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Magistério Superior', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Marketing', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Designer', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Desenho Industrial', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Economia', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Odontologia Facial', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Odontologia Preventiva', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Psicologia Escolar', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Psicologia', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Português p/ Estrangeiros', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Texto, Revisão de', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Recepção', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Física Pré-Vestibular', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Psicopedagogia', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Manutenção', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Vigia', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Ensino Religioso', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Fotografia', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Internet', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Designer Gráfico', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'História da Arte', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Literatura', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Texto, Produção de', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Administrativa, Supervisão', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'História Pensamento Econômico', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Economia Brasileira', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Economia Internacional', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Psicologia da Educação', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Psicologia da Aprendizagem', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Artes Plásticas', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Informática Educacional', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Editoração Eletrônica', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Informática, Laboratório de', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Informática, Analista Prog. Sistema', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Documentação, Centro de', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Arquivo', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Administrativo, Auxiliar', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Pedagógico, Auxiliar', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Digitação', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Orientação Educacional, Aux. de', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Educação p/ Jovens e Adultos', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Volei', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Teatro', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Recreação', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Karatê', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Defesa Pessoal', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Geografia Econômica', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Geografia Ambiental', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Jazz', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Ballet', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Microbiologia', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Material Didático, Autoria de', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Direito Internacional', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Direito Int. Mercosul', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Direito, Introdução ao', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Antropologia', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Quimica, Tecnologia', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Serviço Social', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Matemática Financeira', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Coordenação de Eventos', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Coordenação Financeira', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Coordenação Administrativa', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Meio Ambiente', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Natação', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Hidroginástica', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Fonoaudiologia', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Audiologia Clínica', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Treinamento Desportivo', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Turismo', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Contabilidade Pública', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Contabilidade Geral', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Contábil, Coordenação', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Auditoria', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Contábil, Gerência', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Controladoria', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Engenharia, Disciplina', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Futsal', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Xadrez', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Ciências, Laboratório de', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Nenhuma Opção', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Música', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Coral', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'RH, Analista de', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Coordenação de Esportes', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Volei, Técnico de', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Pedagógica, Analista', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Saúde, Higiene e', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Ginástica Aerolocal', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Software Educativo', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Psicologia Organizacional', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Psicologia Clínica', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Artes Cênicas', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Teoria Geral de Administração', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Musical, Educação', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Administrativo, Assistente', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Lingüística', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Musical, Teoria', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Iniciação Pré-Desportiva', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Treinamento', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Administração', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Botânica', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Ecologia', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Zoologia', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Ciências Agrárias', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Direção, Ass. de', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Ginástica Olímpica', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Pedagógica, Consultoria', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Técnica em Análise', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Consultoria', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Financeiro, Analista', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Coordenação Disciplinar', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Assistente Social', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Cálculo', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Estágio', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Logística', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Telefonista', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Finanças', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Jornalista', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Relações Públicas', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Motorista', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Reabilitação, Técnico em', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Personal Trainer', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Ciência da Computação', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Direção, Aux. de', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Educação Infantil, Atendente de', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Pastoral', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Segurança', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Comercial, Vendedor Área', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Teologia', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Metodologia Científica', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Desenho Técnico', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Geometria Descentiva', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Musculação', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Telemarketing', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Química Ambiental', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Bioquímica', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Teleatendimento', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Caixa', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Educação, Ass. Téc.', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Inglês, Educação Infantil', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Futsal, Técnico de', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Físico, Preparador', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Educação Física/Infantil-Fund. I', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Dança', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Ginástica', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Ética', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'História Ensino Superior', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Comercial, Negociador(a)', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Administrativo, Assessor', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Chefe de Serviço', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Direção, Vice', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Musicoterapia', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Orientação Pedagógica', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Secretária Executiva', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Didática de Ensino', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Química Industrial', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Enfermagem, Aux. de', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Projetos Mecânicos', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Voluntário', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Secretária (o) Acadêmica', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Administração Pública', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Coordenação de Educação Infantil', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Coordenação de Fundamental I', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Coordenação de Fundamental II', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Coordenação de Fundamental I ao Fund. II', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Coordenação de Ensino Médio', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Coordenação de Fundamental I ao Ens. Médio', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Coordenação de Ensino Superior', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Pedagógicos, Projetos', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Direito Civil', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Prática Forense Civel', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Advogado', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Biodireito', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Marketing/Publicidade', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Mídia e Produção', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Gerente de Mudanças', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Eletrônica Digital', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Eletro-Eletrônica', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Gerente de O&M', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Gerente de Produção', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Administração, Prof. de', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Psicologia, Prof.', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Palestrante', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Gestão de Qualidade', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Gestão Ambiental', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Portaria', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Gerente/Restaurante', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Educação Física/Ensino Superior', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Pastoral, Agente de', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Pastoral Familiar', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Judô', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Administrativa, Gerência', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Pastoral, Assessor de', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Financeiro, Ass. Adm', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Filosofia Ensino Superior', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Educação Física Adaptada', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Eletrônica, Técnico em', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Metodologia  Ensino', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Pedagógica, Assessoria', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Ouvidoria', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Tradutor', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Secretária (o) Escolar', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Sociologia da Educação', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Inclusão', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Ciência Política', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Comunicação', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Comercial, Assistente', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Ensino Superior, Prof. de', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Nutrição', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Cobrança, Auxiliar de', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Coordenação Pedagógica', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Aux. de Regência', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'RH, Assistente de', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Depto. Pessoal', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Segurança do Trabalho', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Contínuo', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Office-Boy', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Almoxarife', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Radiologia', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Fisioterapia, Profº de', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Jardineiro', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Tutor(a)', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Educação à Distância', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Psicomotricidade Relacional', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Empreendedorismo', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Odontologia', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Pós Médio, Prof.', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Artes Visuais', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Desenho', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Desenv. de Layout', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Orientação Profissional', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Educacional, Assessor', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Científico, Assessor', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Desenho de Projeto, Téc. de', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Produtor/Rádio', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Depto. Pessoal, Aux. de', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Desenvolv. WEB', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Audio Visual', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Sistema Operacional', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Marketing, Introdução ao', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Gestão de Tecnologia', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Matemática p/ Computação', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Ilustrador', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Saúde, Agente de', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Pastoral, Coordenação de', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Oceanografia', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Biomonitoramento', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Secretaria, Assistente de', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Gestão de Empresa', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Sistema de Inf. Gerenciais - SIG', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Comprador (a)', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Texto, Edição de', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Educação Infantil, (Berçário)', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Vendas', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Orientação Vocacional', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Tutoria', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Enfermagem', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Técnico Profissionalizante, Prof.', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Pedagogia Empresarial', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Contador(a) de Histórias', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Mecanografia', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Material Didático, Análise de', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Informática, Técnico de', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Controladoria, Assistente de', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Informática, Web Designer', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Financeiro, Auxiliar', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Financeiro, Assistente', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Informática, Editoração Eletrônica', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Diagramação', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Depto. Pessoal, Ass. de', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Compras, Assistente de', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Coordenação Pedagógica, Aux. (Ens. Sup)', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Projetos, Prof. de Gerenciamento de', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Projetos, Gerente de', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Serviços Gerais, Encarregada (o)', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Contabilidade, Assistente p/', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Coordenação Pedagógica, Aux.', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Ambiental, Educador', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Coordenação de Pesquisa, Ass. de', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Governanta', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Ioga', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Capacitador/Instrutor', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Atendimento, Encarregado (a) de', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Atendimento, Auxiliar de', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Russo, Professor de Idioma', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Eslováquio, Professor de Idioma', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Árabe, Professor de Idioma', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Holandês, Professor de Idioma', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Texto, Redator', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Comercial, Consultor', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Marketing, Supervisor de', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Gestão de Pessoas', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Manutenção, Encarregado de', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Matemática, Didática da', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Educação, Analista de', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Vigilante', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Enfermagem, Técnico de', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Libras, Professor de', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Tênis, Prof. (a) de', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Projetos Sociais, Assessoria de', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Gastronomia', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'RotinasTrabalhistas', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Direito', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'História Política Externa Brasileira', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Cultura e Poder', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Geografia/Ensino Superior', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Bioética', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Matemática, Estágio p/', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Ensino Superior, Assessoria p/', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Depto. Pessoal, Gerente de', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Depto. Pessoal, Coordenação de', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Depto. Pessoal, Encarregado (a) de', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'RH, Gerente de', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'RH, Coordenador de', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Robótica', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Revisor de Editoração', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Coordenação de Área - Português', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Coordenação de Área - Matemática', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => '1°/5° Ano - Ens. Fund., Atendente p/', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Informática, Prof de (Banco de Dados)', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Iconografia', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Contabilidade, Auxiliar p/', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Analista de Planejamento', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Marketing, Analista de', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Financeira, Gerência', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Educação Infantil, Estágio em', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Mecatrônica', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Texto, Autoria (Material Didático) de', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Expedição, Aux. de', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Informática, Analista de Sistema', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'PCP', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Libras, Intérprete de', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Técnico Pedagógico', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Treinamento e Desenvolvimento, Analista de', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Educação Infantil (Maternal)', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Diagramação', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Arte Finalista', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Analista de Projetos (Licitação)', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Analista de Pesquisa', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Academia, Gerente de', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Secretaria, Encarregada (o) de', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Administração de Rede (Informática)', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Design Instrucional', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Design Educacional', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Tesouraria, Supervisão de', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Tesouraria, Coordenação de', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Tesouraria, Gerência de', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Inglês Fundamental I', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Secretaria, Coordenação de', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Administrativo, Analista', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Educador Social', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Coordenação de Área - Inglês', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Secretária (o) Adjunta Acadêmica', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Aulas em Contra Turno', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Coordenação de Área - Ciências/Biologia', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Coordenação Disciplinar, Aux. de', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Tesouraria, Ass. de', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Informática, Aux. Editoração Eletrônica', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Orientação Disciplinar', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'EAD, Analista de Tecnologia', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'EAD, Web Designer (suporte)', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Gerente de Academia', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Analista de Web Design', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'TI, Suporte Técnico', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Marketing, Coordenação de', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Educação Ambiental', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Coordenação de Área - Aulas Especiais', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Coordenação de Área - Bilingue', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Geografia, Tutoria em', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'História, Tutoria em', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Português, Tutoria em', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'ZCT', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Marketing, Assistente de', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Engenharia, Téc. de Laboratório', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Arquitetura, Téc. de Laboratório', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Tutor Bilingue', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Aux. Bilingue', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Administrativo Acadêmico, Assistente', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Analista Jurídico', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Analista Administrativo', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Capoeira', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Coordenação de Ed. Inf. ao Ens. Fund. I', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Matemática (Ensino Superior)', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Bilinguismo, Prof. (a)', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Psicologia Social', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Atendente de Sala', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Coordenação Fundamental II ao Ensino Médio', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Biblioteca, Analista de', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Educação Física, Prof. Assistente', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Inglês, Prof. Assistente', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Física, Prof. Assistente', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Matemática, Prof. Asistente', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Educação Especial, Profa(o). Aux/Ass.', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Ensino à Distância (EAD), Coordenação de', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Ensino à Distância (EAD), Assistente de', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Inglês, Coordenação de', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Marketing, Gerência de', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Coordenação Adm/Financeira', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Informática, Professor para', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Coordenação de Ed. Inf. ao Ens. Fund. II', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Administrativa/Financeira, Gerência', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Bilíngue, Gerência Nacional', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Consultoria Educacional', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Secretaria Academica (p/pós-graduação)', 'created_at' => now(), 'updated_at' => now()),
            array('uuid' => Str::uuid(), 'name' => 'Pilates', 'created_at' => now(), 'updated_at' => now())
        ));
    }
}
